README.md, package.json, packages/contrast-colors/README.md, packages/contrast-colors/package.json, packages/ui/README.md
Quick updates to the README to prepare for launch, as well as publish tasks to make it happen.
=> docs: launch prep

packages/ui/src/scss/style.scss
=> style: fixed issue with tabs indicator color fallback

packages/ui/src/index.html
=> feat: adding link to demo app in UI

packages/ui/src/demo.css, packages/ui/src/demo.html, packages/ui/src/demo.js
Demo app needed to show more colors and be more of a real-world demo. Chose a calendar UI as this provides an opportunity to display more colors that need varying degrees of contrast.
=> style: Updated demo app to a calendar with more colors to demonstrate

packages/ui/src/demo.css, packages/ui/src/demo.html
style: updated styles of links and reverted buttons with function to open url
=> style: updated styles of links 

packages/ui/src/scss/style.scss
=> style: dropdown width override to correct width

.github/ISSUE_TEMPLATE/--bug-contrast-colors.md, .github/ISSUE_TEMPLATE/--bug-web-tool.md, .github/ISSUE_TEMPLATE/--feature-contrast-colors.md, .github/ISSUE_TEMPLATE/--feature-web-tool.md, .github/PULL_REQUEST_TEMPLATE.md
- Adding Issue templates to help triage issues and gather information
- Corrected URL in comments of the PR templates (above)
=> docs: adding issue and pr templates for github

packages/ui/README.md
Fixes #27 incorrect url in readme
=> fix(ui): Update URL in README

packages/ui/src/index.html, packages/ui/src/index.js
Fixes #23 
Fixes laggy color updates by throttling "Base color" input change event and debouncing "Contrast ratio" inputs input events. This way the event handler is not called too many times which causes the laggy behavior.
=> fix(issue #23) slow color update

packages/ui/src/demo.html, packages/ui/src/index.html
Integrate analytics into Leonardo color web tool as well as demo tool. 
Closes #37
=> added site analytics to index and demo

packages/ui/src/index.html
Local work bled into master branch during `deploySite` 
This removes that content.
=> removed content that bled over from other branch

packages/ui/package.json, packages/ui/src/converter.html, packages/ui/src/converter.js, packages/ui/src/index.html, packages/ui/src/scss/converter.scss, packages/ui/src/scss/style.scss
Incorporated online color converter for all supported colorspaces in Leonardo
Closes #36 
Make it easier to do simple conversions in all supported colorspaces
=> Color converter

packages/ui/src/converter.html, packages/ui/src/converter.js
Converter was missing an option for Hex output -- added in here.
=> feat: added hex to output conversion types

packages/ui/src/converter.html
Fixes #42 
Changed `form` to `div` around converter
=> fix: changed form to div in converter to prevent refresh on submit

packages/ui/src/charts.js, packages/ui/src/index.js
Resolves #52 
Updated to ensure colors applied to data are based on interpolation mode from colorscale and not affected by preview mode.
=> fix: corrected charts with proper colors and data

README.md, packages/contrast-colors/README.md, packages/ui/README.md
Added GitHub badges to readme files
Clearly surface some important information for each package & the top-level repo. Plus they look good.
=> docs: added badges to README files

README.md
Add top-level docs for easier entry to contributing to Leonardo
=> docs: added development instructions to project-level readme

packages/contrast-colors/README.md
* add note about CJS/ESM imports
* fix a few other style things
Document both CJS and ESM usage
=> docs: add note about CJS/ESM imports

packages/ui/package-lock.json, packages/ui/package.json, packages/ui/src/contrast-checker.html, packages/ui/src/contrast-checker.js, packages/ui/src/converter.html, packages/ui/src/converter.js, packages/ui/src/index.html, packages/ui/src/scss/converter.scss, packages/ui/src/theme.html
Adding a contrast checker tool to Leonardo using WCAG relative luminance formula. 
Inputs support all color modes so that teams are not restricted nor require conversion of colors when checking their contrast with this formula.
I realized I was still visiting other tools to do this, and the formula is already in Leonardo and quite simple to add.
=> Contrast checker

packages/contrast-colors/index.d.ts
This adds a new `type` declaration just for color spaces used in the interpolation process and a new `interface` declaration for `colorScales` parameter of `generateAdaptiveTheme`.
This closes #95 and closes #96 
This improves the usage of the package in typescript projects.
=> Improve typescript support

packages/contrast-colors/index.d.ts
Add contrast as an optional parameter in typescript
Closes #98 
- [] This pull request is ready to merge.
=> set contrast to optional in typescript

packages/contrast-colors/index.js, packages/contrast-colors/test/binarySearch.test.js
https://github.com/adobe/leonardo/issues/60
Binary search should return closest value larger than search value 
1. packages\contrast-colors\index.js - Updated binarySearch function to return the closest larger number. If there are no larger numbers, it returns the closest smaller number
2. packages\contrast-colors\test\binarySearch.test.js - Added a test case to return closest match (descending)
=> Issue 60 fix: binary search to return closest larger number

packages/ui/src/scss/converter.scss, packages/ui/src/theme.js
1. Theme UI now passes generated color names (including 'gray' for first color) to the Leonardo Color class instances
2. Corrected width on textfields in contrast checker to avoid wrapping
=> Theme UI bugfixes

packages/contrast-colors/README.md
- Added badges for package size to the readme of contrast-colors package
=> added badges regarding package sizes to contrast-colors readme

packages/contrast-colors/backgroundcolor.js, packages/contrast-colors/chroma-plus.js, packages/contrast-colors/color.js, packages/contrast-colors/curve.js, packages/contrast-colors/test/theme.test.js, packages/contrast-colors/utils.js
Enlarged smooth gradient pre-calculation to improve performance of smooth scale as a part of spectrum-color work.
=> Performance improvements

packages/ui/src/theme.js
- calling `createScale` directly for creating theme scales in the UI
- Theme color gradients were not displaying since they were calling color.colorScale, which returns a function.
=> calling createScale to generate theme ramp

packages/ui/package-lock.json, packages/ui/package.json, yarn.lock
updated colorslider dependency
=> npm & yarn updates

packages/contrast-colors/README.md, packages/contrast-colors/index.js, packages/contrast-colors/package-lock.json, packages/contrast-colors/test/colorSetters.test.js, packages/contrast-colors/test/theme.test.js, packages/contrast-colors/test/themeSetters.test.js, packages/contrast-colors/theme.js
Fixes #138 
- Add saturation parameter to Theme class
- Add setter to theme as `theme.saturation = x`
- Updated docs to include saturation parameter and setter
- Added test for saturation setting along with other setter functions
- Added theme setters to add colors, remove colors, and update color parameters
`updateColor` setter accepts an object with two key-value pairs. The first is the name of the color to be modified. The second is the property to update and the value you wish to update it to.
```
let color = new Color({
name: 'Red',
colorKeys: ['#ff0000', '#ff3200'],
ratios: [3, 4, 5]
});
let theme = new Theme ({
colors: [color]
backgroundColor: '#f5f5f5'
});
theme.updateColor = {name: 'Red', ratios: [4.5, 7, 9]}
```
- Add another dimension to color theme adaptability
- Enhance the …
=> Theme saturation

packages/contrast-colors/theme.js
=> fix: typo in theme constructor for saturation

packages/ui/src/index.js, packages/ui/src/js/params.js
Old URL format was not properly being redirected and converted into arguments for Theme interface.
Redirect and URL reformatting added to retain backwards compatability
=> fix: corrected URL redirect for backwards compatability

packages/ui/src/index.js
Adjustments to the URL redirect function. Previously only included URL's with "index" included in the href. Alternate replacement is necessary for URLs that are at the root and do not explicitly include index.html in the href.
Support existing customer URLs
=> fix: URL redirect

packages/contrast-colors/test/contrast.test.mjs
- Tests for APCA contrast needed updated with the polarity change
=> fixed test for contrast

.moon/toolchain.yml, docs/ui/package.json, docs/ui/src/js/utils.js, package.json, pnpm-lock.yaml
Removed the `&` from the URL sanitization function.
It was causing the share link to not be imported correctly.
#242
=> Fix share link
